### ISSUE TITLE
Group and facet by same variable?

### ISSUE THREAD

**Issue by homerhanumat** [homerhanumat/addinplots#2]
Raised by @rpruim:  permit user to facet by the same variable by which he/she groups?

**Comment by rpruim** [comment]
`lattice` doesn't prohibit this, and it can be useful -- even if just as a transition from one to the other, but also as and end state.

**Comment by homerhanumat** [comment]
OK, I'll make that change.

**Comment by homerhanumat** [comment]
Change made [here](https://github.com/homerhanumat/addinplots/commit/0fc3c7eb65f412b3e8b47bfc9080d2ed1e725b37), but not for barchartAddin where it does not work well.
