### ISSUE TITLE
Froce browser tab to close as part of wrapup?

### ISSUE THREAD

**Issue by homerhanumat** [homerhanumat/addinplots#3]
Raised by @rpruim:  in response to input$done, can we arrange that the browser tab closes?

**Comment by rpruim** [comment]
I don't know whether this is possible, but there seems to be no reason to keep the dead tab open since it doesn't do anything anymore and can't be refreshed either.

**Comment by homerhanumat** [comment]
I am looking into a bit of javascript that should do the trick.

**Comment by homerhanumat** [comment]
This is out of our reach for the moment:

[https://github.com/rstudio/addinexamples/issues/3](https://github.com/rstudio/addinexamples/issues/3)

**Comment by homerhanumat** [comment]
There seems not to be an ideal solution.  To get the window to close upon Done, it has to open in a Pane Viewer or Dialog Viewer.  Pane Viewer is much too small, of ocurse.  But even thought the Dialog Viewer has width and height arguments, it can't go over a certain size.  The app really needs the entire computer screen, as in a browser that the user has maximized, and here we cannot close windows on the user.

**Comment by rpruim** [comment]
Is it at least possible to open the window/tab with a target so that it gets reused rather than spawning a new tab each time the addin is used?  (Apologies if it does this already.)

**Comment by homerhanumat** [comment]
Any locally-run shiny app does the same thing:  if you open it up into a browser window, you have to close the window yourself.  The next app you run will just open a new window.  In the thread referenced above, JJ Allaire and Joe Cheng might be talking about a way around this, but I quite follow what they are saying.
